version: '2'
services:
  web:
    image: odoo:10.0
    restart: always
    depends_on:
      - db
    ports:
      - "8069:8069"
    env_file:
      - ./env/web.env
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
  db:
    image: postgres:9.4
    restart: always
    env_file:
      - ./env/db.env
    ports:
      - 5532:5432/tcp
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
volumes:
  odoo-web-data:
  odoo-db-data:
